(define (problem task5)
   (:domain secrets)
   (:objects a1 a2 a3 a4 a5 a6 - agent s1 s2 - secret)
   (:init 
      (connected a1 a2)
      (connected a2 a4)
      (connected a1 a3)
      (connected a4 a5)
      (connected a3 a5)
      (connected a5 a3)
      (connected a3 a6)
      (deceiver a5)
      (has_belief a1 s1)
      (has_true_belief a1 s1)
   )
   (:goal (and
      (not (has_true_belief a3 s1))
      (has_true_belief a6 s1)
   ))
)
